### ISSUE TITLE
EPH Fails if policy lacks The Manage permission

### ISSUE THREAD

**Issue by itamarla** [Azure/azure-event-hubs-python#16]
When using a policy that has no Manage permission (In cases where a data provider gives you credentials to connect to his EH that lack manage credentials for obvious reasons), the EPH fails with 401 error "Manage claim is required for this operation".

**Comment by xinchen10** [comment]
This is the limitation of the current implementation. EPH needs to know the list of partitions and this information is obtained through a REST/HTTP call now. This call requires Manage claim. Due to other issues we have seen we are experimenting with another AMQP library for underlying protocol communication. With that we will switch to a new RPC over AMQP to obtain partition info which requires Listen claim only.

**Comment by itamarla** [comment]
Would it make sense to add the ability to set the number of partitions as a config param and use it in case the policy does not own management permissions?

**Comment by xinchen10** [comment]
That's possible but may cause unexpected results if someone configures it wrong. We are making process on switching the amqp lib and this is not required when that's done.

**Comment by annatisch** [comment]
The new azure-eventhub SDK no longer uses an HTTP request in order to get the partition info - so this should now be resolved. Let me know if you have any further issues here :)

**Comment by itamarla** [comment]
Cheers for that!
