### ISSUE TITLE
add send/publish example 

### ISSUE THREAD

**Issue by chhantyal** [Azure/azure-event-hubs-python#2]
Since title says `Python client library for Azure Event Hubs`, I hope this issue is not out of scope.

Currently this package only has only receive/subscribe example using Apache Qpid. It would be great to have an working example for sending messages to EventHub.

**Comment by xinchen10** [comment]
This is on our to-do list. Due to resource constraints we haven't made much progress after the initial commits. The receiver only code was published so that it at least can be referenced as an example if one wants to build their application directly on top of Qpid Proton. It may also help to get feedback and contributions while the library is being developed. We hope to continue the development very soon and contributions under any form are always welcome.

**Comment by zluo001** [comment]
For now, there is no azure event hub python sdk to send message via amqp. The official python sdk only implement the HTTP sending, it's very import to those event hub clients running in embedded system. I saw the 'create_sender' function in the sdk, but don't know how to use it. Could you provider an example? Thank you. @xinchen10

**Comment by chhantyal** [comment]
For anyone bumping into this issue, I could not make Qpid Python work with EventHub.

As a workaround, I am now using Java client to connect to EventHub and calling Java from Python :D
You can see examples here https://github.com/chhantyal/azure-eventhub-python

**Comment by xinchen10** [comment]
We just merged develop into master. It has basic examples for send and receive.

**Comment by tomchapin** [comment]
@xinchen10 How is someone supposed to use these python examples in an existing python project? Is there any way you all could release this toolkit as a pip package or something?

**Comment by xinchen10** [comment]
@tomchapin We are still fixing some issues in the client. When it is ready, we will release a pip package.
