### ISSUE TITLE
Example of using offsets for receiver with storage containers?

### ISSUE THREAD

**Issue by AXington** [Azure/azure-event-hubs-python#24]
In the example examples/recv_async.py, the offset is hardcoded to start at -1. I need to use checkpointing with an azure storage container. Does anybody have an example of how to do this anywhere?

**Comment by xinchen10** [comment]
@AXington do you need samples for writing the checkpoint to storage and reading it back on restart? This is storage specific. I think it could be as simple as just storing the offset in a block blob named in your own convention. Once you have the offset you can pass it to subscribe call on restart.

**Comment by annatisch** [comment]
@AXington - is there a reason you prefer not to use EPH for receiving? This will use Azure storage for checkpointing. Otherwise you could take a look at the EPH code to see how it implements storage checkpointing. Here is the bulk of the code here:
https://github.com/Azure/azure-event-hubs-python/blob/master/azure/eventprocessorhost/azure_storage_checkpoint_manager.py

Otherwise I would be happy to adapt one of the existing samples to show storage-based checkpointing but it may take me some time to get to.

**Comment by AXington** [comment]
I forgot to close this. I am not worried about this anymore.
