### ISSUE TITLE
Performance issue while using this library (very high CPU occupancy)

### ISSUE THREAD

**Issue by TomFang123** [Azure/azure-event-hubs-python#58]
While we are using this library,
while we are connecting with our eventhub to get the data and send the data to another eventhub, the CPU is always very high. 
This is the profile from our pycharm:
![image](https://user-images.githubusercontent.com/42800562/44776628-ce473b00-ab78-11e8-8e1a-f49bdc0a32cb.png
[performance issue.pdf](https://github.com/Azure/azure-event-hubs-python/files/2331436/performance.issue.pdf)
)
even if we didn't have data process, this CPU is very high, we found that the majority resource is using on 
<build-in method select.select>, which should be used into select different partition process to handle with the data. 
Currently, our eventhub has 32 partitions, does it means that your library will fork 32 processes for it while python process connected with eventhub? (if yes, that might be problemetic)

**Comment by annatisch** [comment]
Thanks @TomFang123 
We are not forking multiple processes in the SDK.

It appears from the charts that you are running asynchronously via EPH?
In this case of EPH this is running 32 separate EventHub clients on separate connections asynchronously from a single process.
Looking at the supplied details it seems that the client is spending most of it's time working at the connection level which is what we'd expect - maybe we could try to alter the prefetch count to reduce the amount of work done at the connection for each receive?

You can change this setting here:
https://github.com/Azure/azure-event-hubs-python/blob/master/azure/eventprocessorhost/eph.py#L103

You could try dropping it to a value closer to the max batch size, say 40 or so - and see if that makes any difference?

Thanks!

**Comment by TomFang123** [comment]
@annatisch , thanks for your reply.
One question, you mentioned that running 32 separate Eventhub clients on separate connections, is it possible that we can use one Eventhub client to open 32 separate connections to eventHub for its 32 partitions? I think it should be better performance than now. (becasue of Python global interpreter lock, it will also fork 32 processes even if just one eventhub client?)
If it really can improve performance, do you have some of example code for creating one eventhubclient but open 32 separate connections? (currently, the example of this ebh.py in this github repo is based on async which will creating 32 clients under current scenario)
thanks

**Comment by annatisch** [comment]
Thanks @TomFang123 - it seems this issue is tied to uAMQP as reported in [issue 38](https://github.com/Azure/azure-uamqp-python/issues/38)

I will continue to investigate in uAMQP and update both threads as needed.

**Comment by annatisch** [comment]
Hi @TomFang123 - some quick questions:
- What is the message through put like? For example - are there periods where EPH is receiving very few messages per partition? 
- Does CPU usage change in periods of constant message through-put?
- How CPU-intensive is your per-message processing?

**Comment by annatisch** [comment]
I have published a new release of uAMQP with some fixes.

CPU use on idle receive (i.e. no message throughput) and slow receive (low message throughput) should now be at reasonable levels with release 1.0.3.

You can upgrade the uamqp package like so:
`pip install --upgrade uamqp`

CPU will remain quite high with high message throughput, as we prioritize message throughput performance over CPU consumption. In this scenario I would recommend using an external tool to limit the resources available to the process if there's a scenario where it must be kept to a minimum.

For anyone who is not interested in message throughput performance and wishes to slow down the message receiver in order to reduce CPU and memory load, you can do so by lowering the receiver prefetch value and receiving in small batches (`max_batch_size`) for processing.

These options can also be found in the EPH settings:
https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventprocessorhost.eph.ephoptions?view=azure-python
