### ISSUE TITLE
EventProcessorHost loses one partition pump

### ISSUE THREAD

**Issue by tvial** [Azure/azure-event-hubs-python#79]
Hi,

I am using azure-event-hubs-python v1.1.1 with EventProcessorHost in order to listen for messages from a single event hub with 2 partitions. There is one message per minute so one every 2 minutes on each partition (round-robin partition assignment); when an input message is received then an output one is created and sent to another event hub. The application is meant to run continuously.

From time to time, one of the partitions stops receiving input events. It's hard to sift through the verbose, intertwined logs so I would be glad to get some help investigating this. Here are my findings so far.

Usually, when an error occurs (such as the EHSender timing out) within one processing partition, the latter is restarted fine. I can see the partition pump being closed and opened again thanks to the state transition logs (e.g. `<ConnectionState.OPENED: 9>`). However, it seems that if an error occurs **while the pump is being started**, it will not retry and stay in a END state. The particular message I get in the logs:

```
WARNING  azure.eventhub.async_ops 'eventhub.pysdk-83d5640a': All clients failed to start.
```

which lead me to task startup code in `EventHubClientAsync.run_async()`.

Do you confirm that the pump won't recover in such a situation?

In one of my cases, the error occurring during pump startup is not under my control. The root error seems to be:
`The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'`. I suspect this is related to the `idle_timeout` parameter of the AMQP client receiver (60 s is half the message rate per partition), but that parameter is not exposed by the Python API so I'm stuck (I can try to fork the SDK if you think it's worth tuning it). Any thought?

Thanks for your help!

Thomas

**Comment by annatisch** [comment]
Hi @tvial - thanks for the report!

There is logic to reattempt to reconnect the connection if an error occurs during start-up - but its possible that in the interplay between EPH pump and EventHub receiver this logic is not working as it should!

Can you let me know what values you are setting for the [EPHOptions](https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventprocessorhost.eph.ephoptions?view=azure-python)? Specifically these values might assist in your scenario:
- `receive_timeout` - You could try extending this to over to minutes to avoid the timeout
- `release_pump_on_timeout` - Setting this to `True` will mean the pump will shut down cleanly on timeout then reopen from scratch, hopefully avoiding reconnect-attempt-related errors.
- `keep_alive_interval` - This will asynchronously ping the connection at a specified interval (in seconds) to keep an idle connection active in the absence of messages, which should hopefully avoid the "60000 millisecond" error you're seeing.
- `auto_reconnect_on_error` - This is set to `True` by default. By setting to `False` the pump will shutdown and restart from scratch rather than attempting to reconnect, which may clean up some of the error handling.

Lastly - how long is it taking for you to process each Event as it comes through? And if it's a decent period of time (30+ seconds), is it being processed asynchronously? Having a long running synchronous process can leave the connection idle too long which can result in a LinkDetach.

Hopefully some of these settings will help alleviate the errors - let me know how it goes!
Thanks again,
Anna

**Comment by tvial** [comment]
Hi @annatisch,

Thank you for taking the time to help me!
It seems you led me on a very promising track indeed. My code is very much based on the EPH example (https://github.com/Azure/azure-event-hubs-python/blob/master/examples/eph.py) and the `EPHOptions` part had gone out of my mind.

So here are my `EPHOptions`:
- `receive_timeout` is 300 (I remember increasing the value at some point)
- `release_pump_on_timeout` is `True`
- `keep_alive_interval` is left as the default which is `None`
- `auto_reconnect_on_error` is the default `True` as well

Here `release_pump_on_timeout` and `keep_alive_interval` look like good candidates here. Would you advise me to change the values here?

Regarding your other questions: processing an event takes a couple of seconds. The business logic is done synchronously, then the code marks a checkpoint (this is done asynchronously). Is the keep alive mechanism done in the same thread as the `process_events_async()` call?

Thank you once again
Thomas

**Comment by annatisch** [comment]
Hi @tvial - Yes eveything is done in a single thread - as such I would recommend wrapping your synchronous code in an [async wrapper](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor):
```
loop.run_in_executor(None, blocking_function)
```

Try setting `release_pump_on_timeout` to `True`, `auto_reconnect_on_error` to `False` and `keep_alive_interval` to `30` (seconds) and let's see how it goes :)

**Comment by tvial** [comment]
Thank you, it's running in our test environment right now. I'll let a few days pass before I am confident it solved the problem; I'll keep the issue updated.

**Comment by tvial** [comment]
Hi! It's been one week now and the 2 partition pumps are still running fine. Before the modifications, one of them would disappear after a couple of days. As far as I can tell the problem is solved, I'll close the issue.

Let me thank you again for your help in tracking that down, you spotted the problem right away :)

**Comment by annatisch** [comment]
Thanks @tvial for following up! Great to hear it's now running smoothly :)
